
name: 'Terraform'
 
on:
  push:
    branches:
    - main
  pull_request:
 
jobs:
  terraform:
    name: dev
    runs-on: ubuntu-latest
    environment: production
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    defaults:
      run:
        shell: bash
        #working-directory: "./AKS_Terraform"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
     
    - run: cd ./terraform_AKS

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      
    - name: Terraform Init
      id: init
      run: terraform -chdir="./terraform_AKS" init -input=false
      
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: 'Run az commands'
      run: |
          az account set -s "052c9332-2138-411f-adef-e7445d02ecc6"
          pwd

